name: CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
      - master
jobs:
  build:
    strategy:
      matrix: 
        os: [windows-latest]
      fail-fast: false
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup dotnet 8.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'
        source-url: https://nuget.pkg.github.com/nodirmcsd/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    - name: Build and Test
      run: ./Build.ps1
      shell: pwsh
